name: Docker Checks
run-name: Running Docker Checks by ${{ github.actor }}

env:
  ECR_REPOSITORY: azmi1-nodejs-app

on:
  pull_request:
    branches:
      - main
    paths:
      - files/**

jobs:
  Initial-Checks:
    runs-on: ubuntu-latest

    steps:
      - name: Getting initiator name
        run: echo "Workflow initiated by ${{ github.actor }} from branch ${{ github.ref_name }}"

  Docker-Checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./files

    permissions:
      pull-requests: write

    needs: Initial-Checks

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        id: docker-build
        run: docker build -t ${{ env.ECR_REPOSITORY }}:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        id: trivy-scan
        uses: aquasecurity/trivy-action@0.27.0
        with:
          scan-type: "image"
          scan-ref: "${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          format: json
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH,LOW,MEDIUM"
          output: "trivy-report.json"

      # - name: Upload Docker Trivy Report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: trivy-report
      #     path: trivy-report.json

      # - name: Read Trivy scan results
      #   id: read_trivy_results
      #   run: |
      #     SCAN_RESULTS=$(cat trivy-results.json)
      #     echo "results<<EOF" >> $GITHUB_OUTPUT
      #     echo "$SCAN_RESULTS" >> $GITHUB_OUTPUT
      #     echo "EOF" >> $GITHUB_OUTPUT

      - name: Update Pull Request
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('trivy-report.json', 'utf8'));
            let vulnerabilities = '';

            if (report.Results && report.Results.length > 0) {
              vulnerabilities = report.Results.map(result => {
                return `### ${result.Target}\n\n${result.Vulnerabilities.map(vul => `- **${vul.Severity}**: ${vul.Title}`).join('\n')}`;
              }).join('\n\n');
            } else {
              vulnerabilities = 'No vulnerabilities found.';
            }

            const output = `#### Docker Build 🏗️\`${{ steps.docker-build.outcome }}\`
            #### Trivy Scan ⚙️\`${{ steps.trivy-scan.outcome }}\`

            <details><summary>Show Trivy Scan Results</summary>

            \`\`\`${vulnerabilities}\`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
