name: Docker run and test
run-name: Running Docker test and publish by ${{ github.actor }}

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - files/**
