name: Docker image build and publish
run-name: Running Docker image build and publish by ${{ github.actor }}

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - files/**

jobs:
  Get-Tag:
    runs-on: ubuntu-latest
    outputs:
      LATEST_TAG: ${{ steps.get_latest_tag.outputs.LATEST_TAG }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch All Tags
        run: git fetch --tags

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> "$GITHUB_OUTPUT"
          echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)"

      - name: Output Latest Tag
        run: echo "The latest tag is ${{ steps.get_latest_tag.outputs.LATEST_TAG }}"

  Docker-Image-Create-And-Publish:
    runs-on: ubuntu-latest
    needs: Get-Tag
    defaults:
      run:
        shell: bash
        working-directory: files

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build, tag, and push docker image to Amazon ECR Public
        id: build-publish
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          ECR_REGISTRY_ALIAS: sctp-sandbox
          ECR_REPOSITORY: azmi-nodejs-app
          IMAGE_TAG: ${{ jobs.Get-Tag.outputs.LATEST_TAG }}.${{ github.run_number }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REGISTRY_ALIAS/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REGISTRY_ALIAS/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "full_image=$ECR_REGISTRY/$ECR_REGISTRY_ALIAS/$ECR_REPOSITORY:$IMAGE_TAG"

  Docker-Test:
    runs-on: ubuntu-latest
    needs: Docker-Image-Create-And-Publish
    defaults:
      run:
        shell: bash
        working-directory: files

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -no-color -auto-approve

      - name: Export terraform outputs
        id: tfout
        run: |
          terraform output

      - name: Get EC2 Instance ID
        id: ec2-instance
        run: |
          instance_id=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=azmi1-nodejs-ec2" --query "Reservations[].Instances[].InstanceId" --output text)
          echo "::set-output name=instance_id::$instance_id"

      - name: Get EC2 Public IP
        id: ec2-public-ip
        run: |
          ip_address=$(aws ec2 describe-instances --instance-ids ${{ steps.ec2-instance.outputs.instance_id }} --query "Reservations[].Instances[].PublicIpAddress" --output text)
          # echo "Public IP: $ip_address"
          echo "::set-output name=ip_address::$ip_address"

      - name: Pull Docker image from Public ECR
        run: |
          docker pull public.ecr.aws/your-public-repo:your-tag

      - name: Run Docker container on EC2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          ECR_REGISTRY_ALIAS: sctp-sandbox
          ECR_REPOSITORY: azmi-nodejs-app
          IMAGE_TAG: ${{ steps.get_latest_tag.outputs.LATEST_TAG }}.${{ github.run_number }}
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/azmi1-tf-private-key.pem ec2-user@${{ steps.ec2-public-ip.outputs.ip_address }} '
          docker run -dp 8080:8080 $ECR_REGISTRY/$ECR_REGISTRY_ALIAS/$ECR_REPOSITORY:$IMAGE_TAG
          '
