name: "Terraform Destroy"

# Trigger the workflow on pull_request
on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: "type DESTROY to confirm"
        required: true

jobs:
  terraform_destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        if: ${{ github.event.inputs.confirmation }} == "DESTROY"
        id: destroy
        run: terraform destroy -auto-approve
        continue-on-error: true
